server:
  port: ${USER_SERVICE_PORT:8081}


spring:
  webflux:
    base-path: /mood-playlist-service

#PlaylistController endpoints
playlist:
  generate-playlist-by-mood: mood/{mood}
  
#Spotify Client Secret
spotify:
  client-id: ${CLIENT_ID:78fd7bc676ec427295427bce4fbbec7b}
  client-secret: ${CLIENT_SECRET:7e03c6db97a04e0684f245d39e02d1d1}  

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html    

logging:
  level:
    root: info
    reactor.netty.http.client: debug
  
mongo:
    data-base-user-name: ${DATA_BASE_USER_NAME:root}
    data-base-user-password: ${DATA_BASE_USER_PASSWORD:root}
    data-base-host: ${DATA_BASE_HOST:localhost}
    data-base-name: ${DATA_BASE_NAME:MusicDiscovery}